### ISSUE TITLE
Linode functions

### ISSUE THREAD

**Issue by jdppettit** [silverp1/space-personal#14]
Right now we only support making a Linode with one disk image for the full disk space allocated by that plan. It would be great to move to a model where we could allow customers to make disks, config profiles, and so on in Space.

**Comment by jdppettit** [comment]
Would like to see the following:
- ~~linode.update~~
- ~~linode.setrdns~~
- ~~Enable / Disable backups~~
  <-- Isn't exposed via the API: http://i2.kym-cdn.com/photos/images/original/000/173/576/Wat8.jpg

Going to push these over to another release, I don't feel they offer a significant value for the time it will take to implement them (will involve new data models and the like).
- A disk object / disk management options
- A config object / config management options

**Comment by levlaz** [comment]
Do you want to be able to deploy from a stack script? This will add a couple of neat functions (for instance I made one that allows for SSH Keys + Security)

**Comment by jdppettit** [comment]
Maybe, this would require us to keep record of all the Stackscripts or something in the db though, how many are there?

**Comment by levlaz** [comment]
There are a ton of StackScripts, but I was really thinking that we could
just chose the ones that are revelant or known to work. For instance
there are like 30 different LAMP stacks, or ruby stacks. We could chose
the ones that are relevant to our project, or write a couple of our own
to make it super simple to launch one of these stacks, similar to the
one-click installs on DO.

**Comment by jdppettit** [comment]
@levlaz Thats okay with me, do you want to come up with a list of known good StackScripts we should support? I'd like them to be ones that are well maintained (ideally official Linode ones if that is still something you guys do).

**Comment by jdppettit** [comment]
Well, I guess this is done with     15598d2 since I'm pushing back disks / confgs and Linode doesn't offer backups on/off via the API.
