### ISSUE TITLE
Service management

### ISSUE THREAD

**Issue by jdppettit** [silverp1/space-personal#16]
Our goal with Space should be to make it so people don't need to access the command line at all - while that may be impossible to eliminate completely, there are things we can do to make this better overall. One such thing is to allow services to be managed from the UI. 

I think this should live on the Settings page maybe - we already have records of services in the db, so starting/restarting them should be as trivial as making the function to run the start/stop/restart command and add a /utils endpoint to do the needful.

**Comment by jdppettit** [comment]
I added this functionality, but while working through testing I determined that many of these services should not be restarted from within Space, namely:
- Space its self, because it causes a 500 error, might confuse people
- MongoDB, because everything depends on the DB, you would need to manually start it if you stopped it
- Celery, because its a huge pain. 

This leaves us with only 2 services to actually manage, DHCPD and RabbitMQ. While I think it is silly to have this functionality for 2 services, I'm going to leave it in just in case we need thins functionality in the future.

**Comment by levlaz** [comment]
What do you think about creating some sort of watchdog program to make 
sure that everything is up and running? It could just monitor the 
various services required for space and then if something is wrong it 
can either restart the services, bring them up, or let the admin know 
that something isnt working.

**Comment by jdppettit** [comment]
That could work - I already have code in place to check to see if things are running, and more code to start/stop/restart it, so we could pair the two together to accomplish that. Right now that is checking once a minute, do you think that is sufficient?

**Comment by jdppettit** [comment]
Completed basic goals in #23 but I'll keep this open and remove the milestone for discussion about the watch dog service.

**Comment by jdppettit** [comment]
Going to close this out for now, I think the monitoring thing is great but that is kind of a separate issue
