### ISSUE TITLE
Debian/Ubuntu Support 

### ISSUE THREAD

**Issue by levlaz** [silverp1/space-personal#30]
\o/

**Comment by jdppettit** [comment]
:+1:

**Comment by levlaz** [comment]
TODO
- [ ] Remove calls to sudo in the install script 
- [ ] Fix this jenk https://github.com/SpacePanel/space-personal/issues/43
- [ ] Remove virtinst from python requirements, we are installing it as a package AFAIK

**Comment by nickpegg** [comment]
:+1: for removing virtinst from requirements.txt, since PyPI doesn't have that package and the requirement causes `pip install` to fail (at least on Ubuntu 14.04.1).

**Comment by jdppettit** [comment]
We also need to change dhcpd to isc-dhcp-server. This entails:
- Changing that in the setup script
- Confirming the current scheme for dhcpd configuration matches what isc-dhcp-server wants
- Make sure services knows to look for isc-dhcp-server

**Comment by jdppettit** [comment]
0e0dac8 did:
- Fixed #43 - it was thusly closed
- Removed virtinst from requirements

**Comment by jdppettit** [comment]
ce6f9bc removed sudo from setup script

**Comment by jdppettit** [comment]
As far as I can tell this is done, going to do a bit more testing tomorrow, but this should be merged in shortly thereafter.

**Comment by jdppettit** [comment]
Done with #49
