### ISSUE TITLE
space.sh is broken in debian 

### ISSUE THREAD

**Issue by levlaz** [silverp1/space-personal#43]
space.sh calls /etc/init.d/functions which is not a thing in debian. 

In order to solve this issue and prevent others we will write a config file somewhere that other utilities can read and be aware of information about the system. This is a better approach then checking for the OS type multiple times in multiple files.

**Comment by jdppettit** [comment]
This is easy, we just need to have the init script check the dist, the same way we do in setup, and then have it change the source based on that. Proper source for Debian/ubuntu is:

`/lib/lsb/init-functions`

**Comment by jdppettit** [comment]
Fixed it
