### ISSUE TITLE
Assigning IP to server

### ISSUE THREAD

**Issue by ghost** [silverp1/space-personal#52]
Assigning IP address, it results in a 404 error page. 

![screen shot 2015-03-07 at 10 06 38 pm](https://cloud.githubusercontent.com/assets/3976758/6544282/493c7afc-c516-11e4-87f2-66d5738a21b9.png)

**Comment by ghost** [comment]
However, going back to the server, the IP address is assigned.

**Comment by levlaz** [comment]
Thanks for reporting this bug! I may have seen something similar in my testing, I will check it out tonight.

**Comment by jdppettit** [comment]
Derp, the endpoint was renamed at one point and clearly hasn't been updated. That said, the only thing that is broken there is the redirect, will be fixed shortly.

**Comment by ghost** [comment]
You're welcome!

**Comment by levlaz** [comment]
@silverp1 You are too quick, assigning back to you :) :+1:

**Comment by jdppettit** [comment]
Fixed with 4c7b8da closing.
