### ISSUE TITLE
Ubuntu Support

### ISSUE THREAD

**Issue by levlaz** [silverp1/space-personal#6]

**Comment by jdppettit** [comment]
In theory this is just a matter of figuring out what packages we need on Ubuntu. There isn't anything distro specific about Space its self, just the install scripts. If we can get a list of what is needed to make Space function on Ubuntu modifying the install scripts would be trivial.

**Comment by jdppettit** [comment]
Renamed #30 to include Ubuntu also, given that the changes for both should be about the same. Going to close this one as a duplicate.
