### ISSUE TITLE
Got a error when start service

### ISSUE THREAD

**Issue by jiajie999** [silverp1/space-personal#7]
centos6
Python 2.6.6 (r266:84292, Nov 22 2013, 12:16:22) 

Traceback (most recent call last):
  File "space.py", line 5, in <module>
    from utilities import *
  File "/srv/space/utilities.py", line 4, in <module>
    from crontab import CronTab
ImportError: No module named crontab

**Comment by levlaz** [comment]
Hi @jiajie999 thanks for reporting this issue! Just to be clear did you install everything in requirements.txt?

**Comment by jiajie999** [comment]
Hi @levlaz,  I run pip install -r requirements.txt manually and it works! I think something happen when i run ./space.sh.

**Comment by levlaz** [comment]
Hi @jiajie999 thanks so much for the report, we will look into this script and try to get the issue resolved. We appreciate the bug report. :)

**Comment by jdppettit** [comment]
Thanks again for reporting this, pip is now installed and functioning normally as of #10 

Please let me know if you run into further issues.
